'use client';
/* eslint-disable react-hooks/set-state-in-effect -- these effects hydrate browser state and initialize the imperative scene adapter */
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {Orbit,Search,ArrowUpRight,ArrowUp,ArrowDown,ArrowLeft,ArrowRight,ChevronRight,Maximize2,Crosshair,Home as HomeIcon,SlidersHorizontal,HelpCircle,Pause,Play,Send,BookOpen,MoveUpRight,Navigation,ArrowLeftRight,Check,X,RotateCcw,Gauge} from 'lucide-react';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Switch} from '@/components/ui/switch';
import {CommandDialog,CommandInput,CommandList,CommandEmpty,CommandItem,CommandGroup} from '@/components/ui/command';
import {bodies,distance,formatKm,position,AU} from './astronomy';
import type {createScene,SceneOptions,FlightTelemetry} from './scene';
function Picker({value,onChange,items,label}:{value:string;onChange:(v:string)=>void;items:{value:string;label:string}[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{items.map(i=><SelectItem key={i.value} value={i.value}>{i.label}</SelectItem>)}</SelectContent></Select>;}
export default function Home(){
 const host=useRef<HTMLDivElement>(null),engine=useRef<ReturnType<typeof createScene>|null>(null);
 const [selected,setSelected]=useState('earth'),[status,setStatus]=useState('Preparing your spacecraft'),[time,setTime]=useState<number>(0),[ready,setReady]=useState(false),[compatibility,setCompatibility]=useState(false),[error,setError]=useState('');
 const [flight,setFlight]=useState<FlightTelemetry>({mode:'locked',speed:0,target:'earth'});
 const [search,setSearch]=useState(false),[panel,setPanel]=useState<'details'|'guide'|'settings'|'help'|null>(null),[compare,setCompare]=useState('moon'),[visited,setVisited]=useState<string[]>(['earth']),[progressReady,setProgressReady]=useState(false);
 const [options,setOptions]=useState<SceneOptions>({scientific:false,orbits:false,labels:true,reduced:false,rate:0,flightSpeed:1});
 const [question,setQuestion]=useState(''),[answer,setAnswer]=useState(''),[guideSource,setGuideSource]=useState(''),[guideBusy,setGuideBusy]=useState(false);
 const b=bodies.find(b=>b.id===selected)!,other=bodies.find(b=>b.id===compare)!;
 useEffect(()=>{let alive=true;setTime(Date.now());setOptions(o=>({...o,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches}));import('./scene').then(({createScene})=>{if(!alive||!host.current)return;try{engine.current=createScene(host.current,setSelected,setStatus,setTime,id=>setVisited(v=>v.includes(id)?v:[...v,id]),setError,setFlight);setCompatibility(host.current.dataset.renderer==='compatibility');setReady(true);}catch(cause){console.error('Solar system scene failed to start',cause);setError('3D graphics could not start. Try a desktop browser with hardware acceleration enabled. You can still browse world facts below.');}});return()=>{alive=false;engine.current?.dispose();engine.current=null;};},[]);
 useEffect(()=>{engine.current?.setOptions(options);},[options,ready]);
 useEffect(()=>{if(panel||search)engine.current?.brake();},[panel,search]);
 useEffect(()=>{setAnswer('');setQuestion('');setGuideSource('');setCompare(selected==='earth'?'moon':'earth');},[selected]);
 useEffect(()=>{const f=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();setSearch(v=>!v);}};window.addEventListener('keydown',f);return()=>window.removeEventListener('keydown',f);},[]);
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('solar-explorer-progress-v1')||'null');if(Array.isArray(saved?.visited)){const valid=saved.visited.filter((id:unknown)=>typeof id==='string'&&bodies.some(b=>b.id===id));setVisited(Array.from(new Set(['earth',...valid])));}}catch{}finally{setProgressReady(true);}},[]);
 useEffect(()=>{if(progressReady)localStorage.setItem('solar-explorer-progress-v1',JSON.stringify({visited,updatedAt:Date.now()}));},[visited,progressReady]);
 const travel=()=>engine.current?.focus(selected);
 const choose=(id:string)=>{engine.current?.preload(id);setSelected(id);setSearch(false);};
 const lockTarget=()=>engine.current?.lock(selected);
 const returnEarth=()=>{engine.current?.preload('earth');setSelected('earth');setSearch(false);engine.current?.focus('earth');};
 const cancelAction=()=>flight.mode==='assisted'?engine.current?.cancelTravel():engine.current?.brake();
 const ask=async(q:string)=>{const body=b;setQuestion(q);setGuideBusy(true);try{const {answerGuide}=await import('./guide');const result=answerGuide(body,q,time||Date.now());setAnswer(result.answer);setGuideSource(result.source);}finally{setGuideBusy(false);}};
 const touchMove=(code:string,active:boolean)=>engine.current?.setMovement(code,active);
 const km=time?distance(b,other,time):0;
 return <main className="explorer">
 <div ref={host} className="universe" />
 <div className="vignette"/>
 <header className="topbar"><Link className="brand" href="/" aria-label="Solar System Explorer home"><Orbit size={28}/><span>SOLAR SYSTEM<span className="brand-sub">EXPLORER / V1.1</span></span></Link><button className="search-button" onClick={()=>setSearch(true)}><Search size={17}/><span>Find a world</span><kbd>⌘ K</kbd></button><div className="header-actions"><button onClick={()=>setPanel('help')} aria-label="Flight controls"><HelpCircle size={19}/></button><button onClick={()=>setPanel('settings')} aria-label="View settings"><SlidersHorizontal size={19}/></button><button aria-label="Toggle fullscreen" onClick={()=>{if(document.fullscreenElement)document.exitFullscreen();else document.documentElement.requestFullscreen?.().catch(()=>setError('Fullscreen is unavailable in this browser view.'));}}><Maximize2 size={18}/></button></div></header>
 <section className="flight-heading"><span className="eyebrow">YOUR JOURNEY STARTS HERE</span><h1>Where do you<br/>want to go?</h1><p>Ten worlds. Endless perspective.</p></section>
 <div className="view-tools"><span className="eyebrow">GET ORIENTED</span><button onClick={()=>{engine.current?.overview();setOptions(o=>({...o,orbits:true}));}}><Orbit size={17}/>System view</button><button onClick={lockTarget}><Crosshair size={17}/>Lock {b.name}</button><button className="earth-return" onClick={returnEarth}><HomeIcon size={17}/>Return to Earth</button></div>
 {error&&<div className="error-banner" role="alert">{error}<button onClick={()=>setError('')} aria-label="Dismiss message"><X size={16}/></button></div>}
 {!ready&&!error&&<div className="loading">Bringing the solar system into view…</div>}
 <aside className="target-card" aria-label="Selected world"><div className="target-meta"><span className="eyebrow">SELECTED DESTINATION</span><span className="object-index">{String(bodies.indexOf(b)+1).padStart(2,'0')} / 10</span></div><div className="world-title"><h2>{b.name}</h2><span className="body-marker" style={{background:b.color}}/></div><p className="kind">{b.kind}</p><p className="description">{b.description}</p><div className="quick-facts"><div><span>Mean diameter</span><strong>{Math.round(b.radius*2).toLocaleString()} <small>km</small></strong></div><div><span>{b.id==='moon'?'Orbit around Earth':'Orbit around Sun'}</span><strong>{b.year?(b.id==='moon'?'27.3':b.year<1?(b.year*365.25).toFixed(0):b.year.toFixed(1)):'—'} <small>{b.year?(b.year<1?'days':'years'):''}</small></strong></div></div><button className="travel-button" disabled={!ready} onClick={travel}><Navigation size={18}/>{flight.mode==='assisted'?'Change course to':'Travel to'} {b.name}<ArrowUpRight size={19}/></button><button className="details-button" onClick={()=>setPanel('details')}>Explore this world<ChevronRight size={17}/></button></aside>
 <div className="flight-status" data-mode={flight.mode}><span className="status-icon"><Navigation size={16}/></span><div className="status-copy"><span className="eyebrow">SPACECRAFT</span><strong role="status">{status}</strong><span className="telemetry">{flight.mode==='assisted'?`${flight.speed}% route complete`:`Speed ${flight.speed}%`}</span></div><div className="flight-speed-picker"><Gauge size={14}/><Picker label="Flight speed" value={String(options.flightSpeed)} onChange={v=>setOptions(o=>({...o,flightSpeed:Number(v)}))} items={[{value:'0.55',label:'Gentle'},{value:'1',label:'Cruise'},{value:'2',label:'Fast'}]}/></div><button className={flight.mode==='assisted'?'cancel-travel':''} onClick={cancelAction} aria-label={flight.mode==='assisted'?'Cancel assisted travel':'Brake spacecraft'}>{flight.mode==='assisted'?'Cancel travel':'Brake'} <kbd>{flight.mode==='assisted'?'Esc':'Space'}</kbd></button></div>
 <div className="bottom-area"><div className="navigation-top"><div><span className="eyebrow">CHOOSE YOUR NEXT DESTINATION</span><span className="visit-count">{visited.length} / 10 visited · saved on this device</span></div><button className="guide-launch" onClick={()=>setPanel('guide')}><BookOpen size={16}/>Astronomy guide<ArrowUpRight size={16}/></button></div><nav className="world-strip" aria-label="Worlds">{bodies.map((p,i)=><button key={p.id} onClick={()=>choose(p.id)} className={'world-button '+(selected===p.id?'active':'')} aria-pressed={selected===p.id}><span className="world-number">{String(i+1).padStart(2,'0')}</span><span className="swatch" style={{backgroundColor:p.color}}/><span>{p.name}</span>{visited.includes(p.id)&&<Check className="visited-check" size={12}/>}</button>)}</nav><footer className="bottom-bar"><div className="scale-note">{compatibility&&<span title="WebGL is unavailable. A reduced-detail 3D renderer is active.">Compatibility view ·</span>}<span>{options.scientific?'Scientific distances':'Exploration scale'}</span><span>·</span><span>{options.scientific?'Bodies enlarged for visibility':'Distances compressed · bodies enlarged'}</span></div><div className="time-controls"><button aria-label={options.rate?'Pause time':'Play time'} onClick={()=>setOptions(o=>({...o,rate:o.rate?0:1}))}>{options.rate?<Pause size={14}/>:<Play size={14}/>}</button><Picker label="Time speed" value={String(options.rate)} onChange={v=>setOptions(o=>({...o,rate:Number(v)}))} items={[{value:'0',label:'Paused'},{value:'1',label:'Real time'},{value:'1000',label:'1,000×'},{value:'86400',label:'1 day / sec'}]}/><time>{time?new Date(time).toISOString().slice(0,10):'Loading date'} UTC</time></div></footer></div>
 <div className="control-hint"><span>Drag to orbit</span><span>Scroll to approach</span><span><kbd>W A S D</kbd> fly</span><button onClick={()=>setPanel('help')}>All controls</button></div>
 <div className="touch-flight" aria-label="Touch flight controls"><button className="touch-forward" aria-label="Fly forward" onPointerDown={()=>touchMove('KeyW',true)} onPointerUp={()=>touchMove('KeyW',false)} onPointerCancel={()=>touchMove('KeyW',false)} onPointerLeave={()=>touchMove('KeyW',false)}><ArrowUp/></button><button className="touch-left" aria-label="Fly left" onPointerDown={()=>touchMove('KeyA',true)} onPointerUp={()=>touchMove('KeyA',false)} onPointerCancel={()=>touchMove('KeyA',false)} onPointerLeave={()=>touchMove('KeyA',false)}><ArrowLeft/></button><button className="touch-brake" aria-label="Brake touch flight" onClick={()=>engine.current?.brake()}><span>STOP</span></button><button className="touch-right" aria-label="Fly right" onPointerDown={()=>touchMove('KeyD',true)} onPointerUp={()=>touchMove('KeyD',false)} onPointerCancel={()=>touchMove('KeyD',false)} onPointerLeave={()=>touchMove('KeyD',false)}><ArrowRight/></button><button className="touch-back" aria-label="Fly backward" onPointerDown={()=>touchMove('KeyS',true)} onPointerUp={()=>touchMove('KeyS',false)} onPointerCancel={()=>touchMove('KeyS',false)} onPointerLeave={()=>touchMove('KeyS',false)}><ArrowDown/></button></div>
 <CommandDialog open={search} onOpenChange={setSearch} title="Find a world" description="Search the ten worlds available in V1.1."><CommandInput placeholder="Search planets, the Sun or the Moon…"/><CommandList><CommandEmpty>No matching world in V1.1. Try a planet name.</CommandEmpty><CommandGroup heading="Solar system · 10 destinations">{bodies.map(p=><CommandItem key={p.id} value={`${p.name} ${p.kind}`} onSelect={()=>choose(p.id)}><span className="swatch" style={{background:p.color}}/>{p.name}<span className="search-kind">{p.kind}</span></CommandItem>)}</CommandGroup></CommandList></CommandDialog>
 <Sheet open={panel!==null} onOpenChange={open=>{if(!open)setPanel(null);}}><SheetContent className="info-sheet"><SheetTitle>{panel==='details'?b.name:panel==='guide'?'Astronomy guide':panel==='settings'?'Your view':'Flight controls'}</SheetTitle><SheetDescription>{panel==='details'?b.kind:panel==='guide'?`Exploring ${b.name} · Offline curated guide`:panel==='settings'?'A clear distinction between the model and the view.':'Start with assisted travel, then take the controls.'}</SheetDescription>
 {panel==='settings'&&<div className="setting-row"><div><strong>Manual flight speed</strong><p>Choose a forgiving response, balanced cruise, or faster flight.</p></div><Picker label="Manual flight speed" value={String(options.flightSpeed)} onChange={v=>setOptions(o=>({...o,flightSpeed:Number(v)}))} items={[{value:'0.55',label:'Gentle'},{value:'1',label:'Cruise'},{value:'2',label:'Fast'}]}/></div>}
 {panel==='details'&&<><p>{b.description}</p><dl className="detail-grid"><div><dt>Mean radius</dt><dd>{Math.round(b.radius).toLocaleString()} km</dd></div><div><dt>{b.kind.includes('giant')?'Reference-level gravity':'Surface gravity'}</dt><dd>{b.gravity} m/s²</dd></div><div><dt>Sidereal rotation</dt><dd>{Math.abs(b.day).toLocaleString()} hours{b.day<0?' · retrograde':''}</dd></div>{b.id!=='sun'&&<div><dt>Modeled distance from Sun</dt><dd>{time?Math.hypot(...position(b,time)).toFixed(3):'—'} AU</dd></div>}</dl><h3>Atmosphere</h3><p>{b.atmosphere}</p><div className="fact-box"><span className="eyebrow">A CLOSER LOOK</span><p>{b.fact}</p></div><h3><ArrowLeftRight size={18}/>Compare distances</h3><div className="distance-pair"><strong>{b.name}</strong><span>→</span><Picker label="Compare distance with" value={compare} onChange={setCompare} items={bodies.filter(p=>p.id!==selected).map(p=>({value:p.id,label:p.name}))}/></div><div className="distance-result">≈ {formatKm(km)}<small>{(km/AU).toFixed(4)} AU · {(km/299792.458/60).toFixed(2)} light-minutes</small></div><p className="fineprint">Center-to-center straight-line distance at the displayed date. JPL approximate planet model; Earth uses the Earth–Moon barycenter. Moon comparisons use a simplified circular orbit, not a current lunar ephemeris. This is not a flight path.</p><a className="source-link" href={b.source} target="_blank" rel="noreferrer">Read more at NASA<ArrowUpRight size={15}/></a><a className="source-link" href="https://ssd.jpl.nasa.gov/planets/phys_par.html" target="_blank" rel="noreferrer">JPL physical data<ArrowUpRight size={15}/></a><button className="travel-button" disabled={!ready} onClick={()=>{travel();setPanel(null);}}><Navigation size={17}/>Travel to {b.name}<ArrowUpRight size={17}/></button></>}
 {panel==='guide'&&<><div className="guide-note">A deeper offline guide with curated answers and source links. Nothing is sent to an AI service, so it has no usage cost.</div><h3>What would you like to know?</h3><div className="suggestions">{['Could humans live here?','How hot or cold is it?','What missions explored it?','Does it have water?','How long are its day and year?','How far is it from Earth?'].map(q=><button key={q} onClick={()=>ask(q)}>{q}<MoveUpRight size={15}/></button>)}</div><form onSubmit={e=>{e.preventDefault();if(question.trim())ask(question);}} className="ask-form"><input aria-label="Ask about selected world" placeholder={`Ask about ${b.name}…`} value={question} onChange={e=>setQuestion(e.target.value)}/><button aria-label="Ask guide" disabled={!question.trim()||guideBusy}>{guideBusy?<span className="guide-loading">…</span>:<Send size={17}/>}</button></form>{answer&&<div className="guide-answer" aria-live="polite"><span className="eyebrow">ABOUT {b.name.toUpperCase()}</span><p>{answer}</p><a className="source-link" href={guideSource||b.source} target="_blank" rel="noreferrer">Source and further reading<ArrowUpRight size={15}/></a></div>}</>}
 {panel==='settings'&&<><div className="setting-row"><div><strong>Scientific distances</strong><p>True relative distances between planet centers. Body sizes stay enlarged.</p></div><Switch checked={options.scientific} onCheckedChange={v=>setOptions(o=>({...o,scientific:v}))} aria-label="Scientific distances"/></div><div className="setting-row"><div><strong>Orbital paths</strong><p>Trace the approximate elliptical paths of the eight planets.</p></div><Switch checked={options.orbits} onCheckedChange={v=>setOptions(o=>({...o,orbits:v}))} aria-label="Orbital paths"/></div><div className="setting-row"><div><strong>World labels</strong><p>Select a visible name to target a world.</p></div><Switch checked={options.labels} onCheckedChange={v=>setOptions(o=>({...o,labels:v}))} aria-label="World labels"/></div><div className="setting-row"><div><strong>Reduced motion</strong><p>Instant assisted travel and no surface rotation.</p></div><Switch checked={options.reduced} onCheckedChange={v=>setOptions(o=>({...o,reduced:v}))} aria-label="Reduced motion"/></div><div className="progress-setting"><div><strong>Journey progress</strong><p>{visited.length} of 10 worlds visited. Saved in this browser on this device.</p></div><button onClick={()=>{setVisited(['earth']);localStorage.removeItem('solar-explorer-progress-v1');}}><RotateCcw size={15}/>Reset</button></div><h3>About this simulation</h3><p className="fineprint">Planet positions follow JPL’s 1800–2050 approximate Keplerian model, using UTC as an approximation to dynamical time. Orbital speed varies naturally along each ellipse, and body rotation follows the displayed simulation time. The simulation stops at the end of 2049.</p><p className="fineprint">The Moon’s phase and orientation remain illustrative. Atmospheres, lighting, star positions and the curved assisted-travel route are visual approximations. No surface landing or collision physics is simulated.</p><a className="source-link" href="https://ssd.jpl.nasa.gov/planets/approx_pos.html" target="_blank" rel="noreferrer">JPL position model<ArrowUpRight size={15}/></a><h3>Surface imagery</h3><p className="fineprint">Maps by Solar System Scope / INOVE, based on NASA imagery; CC BY 4.0. Colors are enhanced and unmapped regions may contain illustrative terrain. Surface maps load only when needed.</p><a className="source-link" href="https://www.solarsystemscope.com/textures/" target="_blank" rel="noreferrer">Texture credits<ArrowUpRight size={15}/></a><a className="source-link" href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noreferrer">CC BY 4.0 license<ArrowUpRight size={15}/></a></>}
 {panel==='help'&&<><p>Choose a world, then select <b>Travel to</b> for a guided approach. You can cancel at any moment and your selected destination stays visible.</p><dl className="controls-list">{[['Drag','Orbit the locked world'],['Scroll / pinch','Approach or move away'],['Touch arrows','Hold to accelerate on a phone or tablet'],['W / S','Accelerate forward / backward'],['A / D','Strafe left / right'],['Q / E','Descend / climb'],['Arrow keys','Turn smoothly'],['Shift + movement','Temporary speed boost'],['Space','Brake to a stop'],['Esc','Cancel assisted travel'],['⌘ / Ctrl + K','Find any major world']].map(([k,v])=><div key={k}><dt><kbd>{k}</kbd></dt><dd>{v}</dd></div>)}</dl><p>If you lose your bearings, use <b>Lock {b.name}</b> to point toward the selected world without moving, <b>System view</b> for the big picture, or <b>Return to Earth</b> for a guided route home.</p><p className="fineprint">On touchscreens, drag to orbit, pinch to zoom, or hold the on-screen flight arrows. Visited worlds are saved in this browser on this device.</p></>}
 </SheetContent></Sheet>
 </main>;
}
