import * as THREE from 'three';
import {SoftwareRenderer} from './software-renderer';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {bodies,position,Body} from './astronomy';
export type SceneOptions={scientific:boolean;orbits:boolean;labels:boolean;reduced:boolean;rate:number;flightSpeed:number};
export type FlightTelemetry={mode:'locked'|'manual'|'assisted'|'braking';speed:number;target:string};
type AssistedFlight={id:string;start:number;from:THREE.Vector3;look:THREE.Vector3;control:THREE.Vector3;duration:number};
type ViewTransition={start:number;from:THREE.Vector3;look:THREE.Vector3;to:THREE.Vector3;target:THREE.Vector3;duration:number};
export function createScene(host:HTMLDivElement,onSelect:(id:string)=>void,onStatus:(s:string)=>void,onTime:(t:number)=>void,onVisit:(id:string)=>void,onError:(s:string)=>void,onTelemetry:(state:FlightTelemetry)=>void){
 let renderer:THREE.WebGLRenderer|SoftwareRenderer;
 const webglCanvas=document.createElement('canvas');
 const webglContext=webglCanvas.getContext('webgl2',{antialias:true,alpha:false,powerPreference:'high-performance'})||webglCanvas.getContext('webgl',{antialias:true,alpha:false,powerPreference:'high-performance'});
 try{renderer=webglContext?new THREE.WebGLRenderer({canvas:webglCanvas,context:webglContext,antialias:true,alpha:false,powerPreference:'high-performance'}):new SoftwareRenderer();}catch{renderer=new SoftwareRenderer();}
 if(renderer instanceof SoftwareRenderer)host.dataset.renderer='compatibility';
 if(!host.dataset.renderer)host.dataset.renderer='webgl';
 renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor('#01040a');renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.03;
 host.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','Interactive 3D solar system. Drag to look around; use WASD to fly.');renderer.domElement.tabIndex=0;
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(43,1,.01,100000);
 const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.08;controls.enablePan=true;controls.maxDistance=12000;controls.minDistance=.05;
 const ambient=new THREE.AmbientLight('#8ca3bf',.045);scene.add(ambient);const sunlight=new THREE.PointLight('#fff4df',4.4,0,0);sunlight.castShadow=true;sunlight.shadow.mapSize.set(1024,1024);sunlight.shadow.bias=-.0002;scene.add(sunlight);if(renderer instanceof THREE.WebGLRenderer){renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;}
 let options:SceneOptions={scientific:false,orbits:false,labels:true,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches,rate:0,flightSpeed:1};
 let time=Date.now(),focused='earth',follow=true,disposed=false,flight:AssistedFlight|null=null,viewTransition:ViewTransition|null=null,aim:{id:string;start:number;from:THREE.Vector3}|null=null,braking=false,last=performance.now(),lastNotify=0,lastFlightStatus=0,frame=0;const keys=new Set<string>();
 const velocity=new THREE.Vector3(),angularVelocity=new THREE.Vector2();let manualSpeedPercent=0;
 const loader=new THREE.TextureLoader(),textures:THREE.Texture[]=[];const labels:HTMLButtonElement[]=[];const groups=new Map<string,THREE.Group>(),meshes:THREE.Mesh[]=[];const sizes=new Map<string,number>(),surfaceMaterials=new Map<string,THREE.MeshBasicMaterial|THREE.MeshStandardMaterial>();const loadedSurfaces=new Set<string>();const orbits=new THREE.Group();let cloudMaterial:THREE.MeshStandardMaterial|null=null,ringMaterial:THREE.MeshStandardMaterial|null=null,routeLine:THREE.Line|null=null;scene.add(orbits);
 const loadTexture=(name:string,onLoad:(texture:THREE.Texture)=>void,colorSpace:THREE.ColorSpace=THREE.SRGBColorSpace)=>{const t=loader.load('/textures/'+name,(texture)=>{if(disposed){texture.dispose();return;}onLoad(texture);},undefined,()=>onError('A surface map could not load. Refresh to retry.'));t.colorSpace=colorSpace;t.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());textures.push(t);};
 function world(b:Body,at=time):THREE.Vector3{const v=new THREE.Vector3(...position(b,at));if(options.scientific)return v.multiplyScalar(100);
 if(b.id==='moon'){const earth=bodies[3];return world(earth,at).add(v.sub(new THREE.Vector3(...position(earth,at))).normalize().multiplyScalar(5));}
 const len=v.length();return len?v.multiplyScalar((24+Math.log1p(len)*38)/len):v;}
 function radius(b:Body){return b.id==='sun'?5:Math.max(.38,Math.pow(b.radius/6371,.5)*1.4);}
 for(const b of bodies){
 const r=radius(b);sizes.set(b.id,r);const g=new THREE.Group();g.position.copy(world(b));scene.add(g);groups.set(b.id,g);
 const material=b.id==='sun'?new THREE.MeshBasicMaterial({color:b.color}):new THREE.MeshStandardMaterial({color:b.color,roughness:b.id==='earth'?.68:b.kind.includes('giant')?.92:.84,metalness:0});surfaceMaterials.set(b.id,material);
 const mobile=matchMedia('(max-width: 760px), (pointer: coarse)').matches;const m=new THREE.Mesh(new THREE.SphereGeometry(r,mobile?48:72,mobile?32:48),material);m.rotation.z=(b.id==='uranus'?97.8:b.id==='earth'?23.44:b.id==='saturn'?26.7:3)*Math.PI/180;m.userData.id=b.id;m.castShadow=b.id!=='sun';m.receiveShadow=b.id!=='sun';g.add(m);meshes.push(m);
 if(b.id==='sun'){const glowCanvas=document.createElement('canvas');glowCanvas.width=glowCanvas.height=256;const ctx=glowCanvas.getContext('2d')!,gradient=ctx.createRadialGradient(128,128,30,128,128,128);gradient.addColorStop(0,'rgba(255,245,210,.3)');gradient.addColorStop(.22,'rgba(255,206,108,.14)');gradient.addColorStop(.55,'rgba(255,142,48,.045)');gradient.addColorStop(1,'rgba(255,105,24,0)');ctx.fillStyle=gradient;ctx.fillRect(0,0,256,256);const glowTexture=new THREE.CanvasTexture(glowCanvas);textures.push(glowTexture);const corona=new THREE.Sprite(new THREE.SpriteMaterial({map:glowTexture,color:'#ffd39a',transparent:true,opacity:.58,blending:THREE.AdditiveBlending,depthWrite:false}));corona.scale.setScalar(r*7);g.add(corona);}
 if(b.id==='earth'){
 cloudMaterial=new THREE.MeshStandardMaterial({color:'white',roughness:1,transparent:true,opacity:0,depthWrite:false});
 const cloud=new THREE.Mesh(new THREE.SphereGeometry(r*1.008,mobile?40:56,mobile?28:40),cloudMaterial);m.add(cloud);
 const glow=new THREE.Mesh(new THREE.SphereGeometry(r*1.035,64,48),new THREE.ShaderMaterial({uniforms:{tint:{value:new THREE.Color('#4b9ee8')}},vertexShader:'varying vec3 n;varying vec3 v;varying vec3 wp;void main(){wp=(modelMatrix*vec4(position,1.)).xyz;n=normalize(mat3(modelMatrix)*normal);v=normalize(cameraPosition-wp);gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec3 n;varying vec3 v;varying vec3 wp;uniform vec3 tint;void main(){float rim=pow(1.-max(dot(normalize(n),normalize(v)),0.),3.5);float day=smoothstep(-.28,.18,dot(normalize(n),normalize(-wp)));gl_FragColor=vec4(tint,rim*(.08+.32*day));}',side:THREE.BackSide,transparent:true,depthWrite:false,blending:THREE.AdditiveBlending}));g.add(glow);
 }
 if(b.id==='saturn'){
 const ringGeo=new THREE.RingGeometry(r*1.24,r*2.3,192,4);const uv=ringGeo.attributes.uv,p=ringGeo.attributes.position;for(let i=0;i<p.count;i++){const len=Math.hypot(p.getX(i),p.getY(i));uv.setXY(i,(len-r*1.24)/(r*1.06),.5);}
 ringMaterial=new THREE.MeshStandardMaterial({color:'#c9b58f',roughness:.94,metalness:0,transparent:true,side:THREE.DoubleSide,depthWrite:false,alphaTest:.025,opacity:.84});const ring=new THREE.Mesh(ringGeo,ringMaterial);ring.rotation.x=-Math.PI/2;ring.castShadow=true;ring.receiveShadow=true;const tilt=new THREE.Group();tilt.rotation.z=26.7*Math.PI/180;tilt.add(ring);g.add(tilt);
 }
 const label=document.createElement('button');label.className='world-label';label.textContent=b.name;label.setAttribute('aria-label','Select '+b.name);label.addEventListener('click',()=>onSelect(b.id));host.appendChild(label);labels.push(label);
 }
 function preload(id:string){if(loadedSurfaces.has(id))return;const body=bodies.find(b=>b.id===id);const material=surfaceMaterials.get(id);if(!body||!material)return;loadedSurfaces.add(id);loadTexture(body.texture+'.jpg',texture=>{material.map=texture;material.color.set('#ffffff');material.needsUpdate=true;});if(id==='earth'&&cloudMaterial)loadTexture('earth_clouds.jpg',texture=>{if(!cloudMaterial)return;cloudMaterial.alphaMap=texture;cloudMaterial.opacity=.68;cloudMaterial.needsUpdate=true;},THREE.NoColorSpace);if(id==='saturn'&&ringMaterial)loadTexture('saturn_ring_alpha.png',texture=>{if(!ringMaterial)return;ringMaterial.map=texture;ringMaterial.color.set('#ffffff');ringMaterial.opacity=.94;ringMaterial.needsUpdate=true;});}
 preload('earth');preload('sun');
 // A decorative star field, not a catalogue of observed stellar positions.
 const stars=new Float32Array(15000),starColors=new Float32Array(15000);let seed=12345;const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};for(let i=0;i<stars.length;i+=3){const z=rand()*2-1,a=rand()*Math.PI*2,r=14000,warm=rand(),brightness=.48+Math.pow(rand(),6)*.52;stars[i]=Math.sqrt(1-z*z)*Math.cos(a)*r;stars[i+1]=z*r;stars[i+2]=Math.sqrt(1-z*z)*Math.sin(a)*r;starColors[i]=brightness*(warm>.88?1:.74);starColors[i+1]=brightness*(warm>.88?.86:.86);starColors[i+2]=brightness*(warm>.88?.7:1);}
 const starGeo=new THREE.BufferGeometry();starGeo.setAttribute('position',new THREE.BufferAttribute(stars,3));starGeo.setAttribute('color',new THREE.BufferAttribute(starColors,3));const starfield=new THREE.Points(starGeo,new THREE.PointsMaterial({vertexColors:true,size:1.15,sizeAttenuation:false,transparent:true,opacity:.72,depthWrite:false}));scene.add(starfield);
 function rebuildOrbits(){for(const c of [...orbits.children]){orbits.remove(c);(c as THREE.Line).geometry.dispose();((c as THREE.Line).material as THREE.Material).dispose();}
 for(const b of bodies.filter(b=>b.elements)){
 const points=[];for(let i=0;i<=256;i++){const v=new THREE.Vector3(...position(b,time,i/256*Math.PI*2));const len=v.length();points.push(options.scientific?v.multiplyScalar(100):v.multiplyScalar((24+Math.log1p(len)*38)/len));}
 orbits.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color:'#7897a1',transparent:true,opacity:.15,depthWrite:false})));}orbits.visible=options.orbits;}
 rebuildOrbits();
 function destination(id:string){const p=world(bodies.find(b=>b.id===id)!);const dir=p.length()>.1?p.clone().normalize().negate():new THREE.Vector3(.5,.2,1);dir.applyAxisAngle(new THREE.Vector3(0,1,0),-.6);dir.y=.35;dir.normalize();return {p,c:p.clone().addScaledVector(dir,sizes.get(id)!*(id==='saturn'?9.2:4.6))};}
 function clearRoute(){if(!routeLine)return;scene.remove(routeLine);routeLine.geometry.dispose();(routeLine.material as THREE.Material).dispose();routeLine=null;}
 function flightPoint(from:THREE.Vector3,control:THREE.Vector3,to:THREE.Vector3,t:number){const a=(1-t)*(1-t),b=2*(1-t)*t,c=t*t;return from.clone().multiplyScalar(a).addScaledVector(control,b).addScaledVector(to,c);}
 function focus(id:string,instant=false){focused=id;follow=false;braking=false;aim=null;viewTransition=null;keys.clear();velocity.set(0,0,0);angularVelocity.set(0,0);preload(id);const body=bodies.find(b=>b.id===id)!;onStatus(instant?body.name+' locked':'Plotting course to '+body.name);const d=destination(id);controls.minDistance=sizes.get(id)!*1.12;clearRoute();
 if(instant||options.reduced){camera.position.copy(d.c);controls.target.copy(d.p);flight=null;follow=true;onStatus(body.name+' locked');onTelemetry({mode:'locked',speed:0,target:id});onVisit(id);}
 else{const from=camera.position.clone(),span=from.distanceTo(d.c),control=from.clone().lerp(d.c,.5),outward=control.clone().normalize();if(outward.lengthSq()<.01)outward.set(0,1,0);control.addScaledVector(outward,Math.min(90,Math.max(5,span*.2)));control.y+=Math.min(45,span*.1);const duration=Math.min(6500,Math.max(2600,2300+Math.log1p(span)*850));const points=[];for(let i=0;i<=48;i++)points.push(flightPoint(from,control,d.c,i/48));routeLine=new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineDashedMaterial({color:'#a8e3cf',transparent:true,opacity:.34,dashSize:1.4,gapSize:1}));routeLine.computeLineDistances();scene.add(routeLine);flight={id,start:performance.now(),from,look:controls.target.clone(),control,duration};}}
 focus('earth',true);onTime(time);
 function resize(){const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();}const observer=new ResizeObserver(resize);observer.observe(host);resize();
 const targetName=()=>bodies.find(b=>b.id===focused)!.name;
 const stop=()=>{const wasAssisted=!!flight;flight=null;viewTransition=null;aim=null;camera.fov=43;camera.updateProjectionMatrix();clearRoute();follow=false;if(wasAssisted)onStatus('Travel cancelled · '+targetName()+' remains selected');else onStatus('Manual flight');};
 const lock=(id:string)=>{focused=id;flight=null;viewTransition=null;braking=false;keys.clear();velocity.set(0,0,0);angularVelocity.set(0,0);clearRoute();follow=false;preload(id);controls.minDistance=sizes.get(id)!*1.12;if(options.reduced){controls.target.copy(world(bodies.find(b=>b.id===id)!));follow=true;}else aim={id,start:performance.now(),from:controls.target.clone()};onStatus(targetName()+' locked · ready to travel');onTelemetry({mode:'locked',speed:0,target:id});};
 const brake=()=>{keys.clear();flight=null;viewTransition=null;aim=null;camera.fov=43;camera.updateProjectionMatrix();clearRoute();follow=false;braking=true;angularVelocity.set(0,0);onStatus('Braking…');onTelemetry({mode:'braking',speed:Math.round(velocity.length()),target:focused});};
 const cancelTravel=()=>{keys.clear();flight=null;viewTransition=null;aim=null;camera.fov=43;camera.updateProjectionMatrix();braking=false;clearRoute();velocity.set(0,0,0);angularVelocity.set(0,0);follow=false;onStatus('Travel cancelled · '+targetName()+' remains selected');onTelemetry({mode:'manual',speed:0,target:focused});};
 controls.addEventListener('start',()=>{if(flight)stop()});
 const down=(e:KeyboardEvent)=>{if((e.target as HTMLElement).closest('input,textarea,select,[role="dialog"],[role="combobox"]'))return;if(['KeyW','KeyA','KeyS','KeyD','KeyQ','KeyE','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','ShiftLeft','ShiftRight','Space','Escape'].includes(e.code)){e.preventDefault();if(e.code==='Space'){brake();return;}if(e.code==='Escape'){cancelTravel();return;}keys.add(e.code);braking=false;stop();}};
 const up=(e:KeyboardEvent)=>keys.delete(e.code),blur=()=>keys.clear();window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);
 let pointerStart=[0,0];const pd=(e:PointerEvent)=>{pointerStart=[e.clientX,e.clientY];};const pu=(e:PointerEvent)=>{if(Math.hypot(e.clientX-pointerStart[0],e.clientY-pointerStart[1])>5)return;const rect=renderer.domElement.getBoundingClientRect();const ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),camera);const hit=ray.intersectObjects(meshes,false)[0];if(hit)onSelect(hit.object.userData.id);};renderer.domElement.addEventListener('pointerdown',pd);renderer.domElement.addEventListener('pointerup',pu);
 const contextLost=(e:Event)=>{e.preventDefault();onError('The 3D connection was interrupted. Refresh this page to restart.');};renderer.domElement.addEventListener('webglcontextlost',contextLost);
 function animate(now:number){if(disposed)return;frame=requestAnimationFrame(animate);const elapsed=Math.min((now-last)/1000,.25);const dt=Math.min(elapsed,.05);last=now;const previous=world(bodies.find(b=>b.id===focused)!);time=Math.min(Date.UTC(2049,11,31),time+elapsed*1000*options.rate);
 for(const b of bodies){groups.get(b.id)!.position.copy(world(b));const mesh=meshes[bodies.indexOf(b)];if(!options.reduced&&host.dataset.renderer!=='compatibility'){mesh.rotation.y=(((time-Date.UTC(2000,0,1,12))/3600000/b.day)*Math.PI*2)%(Math.PI*2);if(b.id==='earth'&&mesh.children[0])mesh.children[0].rotation.y=mesh.rotation.y*.07;}}
 const current=world(bodies.find(b=>b.id===focused)!);if(follow&&!flight&&!viewTransition&&!aim){const delta=current.clone().sub(previous);camera.position.add(delta);controls.target.add(delta);}
 if(flight){const t=Math.min(1,(now-flight.start)/flight.duration),e=t*t*t*(t*(t*6-15)+10),d=destination(flight.id);camera.position.copy(flightPoint(flight.from,flight.control,d.c,e));controls.target.lerpVectors(flight.look,d.p,e);camera.fov=43+Math.sin(t*Math.PI)*2.2;camera.updateProjectionMatrix();if(now-lastFlightStatus>300&&t<1){lastFlightStatus=now;const pct=Math.round(t*100);onStatus(`Cruising to ${bodies.find(b=>b.id===flight.id)!.name} · ${pct}%`);onTelemetry({mode:'assisted',speed:pct,target:flight.id});}if(t===1){onVisit(flight.id);flight=null;camera.fov=43;camera.updateProjectionMatrix();clearRoute();follow=true;onStatus(targetName()+' locked');onTelemetry({mode:'locked',speed:0,target:focused});}}
 if(viewTransition){const t=Math.min(1,(now-viewTransition.start)/viewTransition.duration),e=t*t*t*(t*(t*6-15)+10);camera.position.lerpVectors(viewTransition.from,viewTransition.to,e);controls.target.lerpVectors(viewTransition.look,viewTransition.target,e);camera.fov=43+Math.sin(t*Math.PI)*1.4;camera.updateProjectionMatrix();if(t===1){viewTransition=null;camera.fov=43;camera.updateProjectionMatrix();onStatus('Solar system overview · choose a world anytime');}}
 if(aim){const t=Math.min(1,(now-aim.start)/850),e=t*t*(3-2*t);controls.target.lerpVectors(aim.from,world(bodies.find(b=>b.id===aim!.id)!),e);if(t===1){aim=null;follow=true;}}
 const direction=new THREE.Vector3();camera.getWorldDirection(direction);const right=new THREE.Vector3().crossVectors(direction,camera.up).normalize();
 const translating=['KeyW','KeyA','KeyS','KeyD','KeyQ','KeyE'].some(code=>keys.has(code));
 if(!flight&&!viewTransition&&!aim){const distanceScale=Math.max(sizes.get(focused)!*.8,camera.position.distanceTo(controls.target)*.22),acceleration=distanceScale*options.flightSpeed*(keys.has('ShiftLeft')||keys.has('ShiftRight')?2.8:1),maxSpeed=acceleration*2.4;const thrust=new THREE.Vector3();if(keys.has('KeyW'))thrust.add(direction);if(keys.has('KeyS'))thrust.sub(direction);if(keys.has('KeyA'))thrust.sub(right);if(keys.has('KeyD'))thrust.add(right);if(keys.has('KeyQ'))thrust.y-=1;if(keys.has('KeyE'))thrust.y+=1;if(thrust.lengthSq())velocity.addScaledVector(thrust.normalize(),acceleration*dt);if(velocity.length()>maxSpeed)velocity.setLength(maxSpeed);const drag=braking?Math.exp(-10*dt):Math.exp(-(translating?.55:2.2)*dt);velocity.multiplyScalar(drag);manualSpeedPercent=Math.round(Math.min(1,velocity.length()/maxSpeed)*100);if(velocity.length()<.002){velocity.set(0,0,0);manualSpeedPercent=0;if(braking){braking=false;onStatus('Stopped · '+targetName()+' remains selected');}}camera.position.addScaledVector(velocity,dt);controls.target.addScaledVector(velocity,dt);
 const yaw=(keys.has('ArrowLeft')?1:0)-(keys.has('ArrowRight')?1:0),pitch=(keys.has('ArrowUp')?1:0)-(keys.has('ArrowDown')?1:0),turnBlend=1-Math.exp(-7*dt);angularVelocity.x+=(yaw*1.25-angularVelocity.x)*turnBlend;angularVelocity.y+=(pitch*.95-angularVelocity.y)*turnBlend;if(!yaw)angularVelocity.x*=Math.exp(-5*dt);if(!pitch)angularVelocity.y*=Math.exp(-5*dt);if(Math.abs(angularVelocity.x)+Math.abs(angularVelocity.y)>.001){direction.applyAxisAngle(camera.up,angularVelocity.x*dt);direction.applyAxisAngle(right,angularVelocity.y*dt);controls.target.copy(camera.position).addScaledVector(direction,Math.max(1,camera.position.distanceTo(controls.target)));}
 }
 // Keep the camera outside each exaggerated body, including when manual flight crosses a surface.
 for(const b of bodies){const p=groups.get(b.id)!.position,r=sizes.get(b.id)!*1.08,offset=camera.position.clone().sub(p);if(offset.length()<r){const correction=offset.normalize().multiplyScalar(r).add(p).sub(camera.position);camera.position.add(correction);controls.target.add(correction);}}
 controls.update();starfield.position.copy(camera.position);
 const viewDirection=new THREE.Vector3();camera.getWorldDirection(viewDirection);
 bodies.forEach((b,i)=>{const p=world(b),r=sizes.get(b.id)!;const visible=options.labels&&p.clone().sub(camera.position).dot(viewDirection)>0;const screen=p.clone().add(new THREE.Vector3(0,r*1.25,0)).project(camera);const label=labels[i];label.style.display=visible&&Math.abs(screen.x)<.95&&Math.abs(screen.y)<.86&&screen.z<1?'block':'none';label.style.left=(screen.x*.5+.5)*host.clientWidth+'px';label.style.top=(-screen.y*.5+.5)*host.clientHeight+'px';});
 if(!document.querySelector('[role="dialog"][data-state="open"]'))renderer.render(scene,camera);if(now-lastNotify>250){lastNotify=now;onTime(time);if(!flight)onTelemetry({mode:braking?'braking':velocity.length()>.01||keys.size?'manual':follow?'locked':'manual',speed:manualSpeedPercent,target:focused});}}
 frame=requestAnimationFrame(animate);
 return {focus,lock,cancelTravel,preload,overview(){stop();focused='sun';preload('sun');braking=false;velocity.set(0,0,0);angularVelocity.set(0,0);controls.minDistance=.05;const range=options.scientific?3700:205,to=new THREE.Vector3(0,range*1.3,range*.65),target=new THREE.Vector3();if(options.reduced){camera.position.copy(to);controls.target.copy(target);onStatus('Solar system overview · choose a world anytime');}else{viewTransition={start:performance.now(),from:camera.position.clone(),look:controls.target.clone(),to,target,duration:1800};onStatus('Opening solar system view…');}onTelemetry({mode:'manual',speed:0,target:'sun'});},brake,setMovement(code:string,active:boolean){if(active){keys.add(code);braking=false;stop();}else keys.delete(code);},setOptions(next:SceneOptions){const scale=options.scientific!==next.scientific;options=next;orbits.visible=options.orbits;if(scale){for(const b of bodies){const scaleFactor=options.scientific?.05:1;groups.get(b.id)!.scale.setScalar(scaleFactor);sizes.set(b.id,radius(b)*scaleFactor);}rebuildOrbits();focus(focused,true);}},dispose(){disposed=true;keys.clear();clearRoute();cancelAnimationFrame(frame);observer.disconnect();window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);controls.dispose();textures.forEach(t=>t.dispose());scene.traverse(o=>{const m=o as THREE.Mesh;if(m.geometry)m.geometry.dispose();if(m.material){(Array.isArray(m.material)?m.material:[m.material]).forEach(mat=>mat.dispose());}});renderer.dispose();renderer.domElement.remove();labels.forEach(l=>l.remove());}};
}
