// Canvas compatibility renderer. Uses the same Three.js camera and scene graph;
// ray/sphere intersections preserve free flight and perspective without WebGL.
/* eslint-disable @typescript-eslint/no-unused-expressions -- compact hot-path drawing expressions are intentional */
import * as THREE from 'three';
export class SoftwareRenderer{
 domElement=document.createElement('canvas');capabilities={getMaxAnisotropy:()=>1};outputColorSpace:THREE.ColorSpace=THREE.SRGBColorSpace;toneMapping:THREE.ToneMapping=THREE.NoToneMapping;toneMappingExposure=1;private width=1;private height=1;private last=0;private lastForced=0;private signature='';
 private ctx=this.domElement.getContext('2d')!;private pixels=new Map<string,{data:Uint8ClampedArray;width:number;height:number}>();private globe=document.createElement('canvas');private gctx=this.globe.getContext('2d')!;private stars:THREE.Vector3[]=[];
 constructor(){this.globe.width=128;this.globe.height=128;let n=42;const rand=()=>{n=(n*1664525+1013904223)>>>0;return n/4294967296;};for(let i=0;i<850;i++){const z=rand()*2-1,a=rand()*6.283;this.stars.push(new THREE.Vector3(Math.sqrt(1-z*z)*Math.cos(a),z,Math.sqrt(1-z*z)*Math.sin(a)));}}
 setPixelRatio(value:number){void value;}setClearColor(value:THREE.ColorRepresentation){void value;}setSize(w:number,h:number){this.width=w;this.height=h;this.domElement.width=w;this.domElement.height=h;this.domElement.style.width=w+'px';this.domElement.style.height=h+'px';}dispose(){this.pixels.clear();}
 private texture(t:THREE.Texture|null){const image=t?.image as HTMLImageElement|undefined;if(!t||!image?.width)return null;const key=t.uuid;let p=this.pixels.get(key);if(!p){const c=document.createElement('canvas');c.width=image.width;c.height=image.height;const ctx=c.getContext('2d',{willReadFrequently:true})!;ctx.drawImage(image,0,0);p={data:ctx.getImageData(0,0,c.width,c.height).data,width:c.width,height:c.height};this.pixels.set(key,p);}return p;}
 render(scene:THREE.Scene,camera:THREE.PerspectiveCamera){const now=performance.now();if(now-this.last<110)return;const signature=[camera.position.x,camera.position.y,camera.position.z,camera.quaternion.x,camera.quaternion.y,camera.quaternion.z,camera.quaternion.w].map(n=>n.toFixed(4)).join(',');if(signature===this.signature&&now-this.lastForced<1500)return;this.last=now;this.lastForced=now;this.signature=signature;scene.updateMatrixWorld(true);camera.updateMatrixWorld(true);const ctx=this.ctx,w=this.width,h=this.height,bg=ctx.createRadialGradient(w*.48,h*.43,0,w*.48,h*.43,Math.max(w,h)*.78);bg.addColorStop(0,'#07101b');bg.addColorStop(.48,'#020812');bg.addColorStop(1,'#010307');ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);
 const cameraInv=camera.quaternion.clone().invert(),f=h/(2*Math.tan(camera.fov*Math.PI/360));
 for(let i=0;i<this.stars.length;i++){const v=this.stars[i].clone().applyQuaternion(cameraInv);if(v.z>=0)continue;const x=w/2+v.x/-v.z*f,y=h/2-v.y/-v.z*f;if(x<0||x>w||y<0||y>h)continue;const bright=i%29===0,warm=i%47===0;ctx.fillStyle=bright?(warm?'#ffe0bdcc':'#dceeffc4'):(i%7===0?'#c5d9ed70':'#9eb5cf45');ctx.fillRect(x,y,bright?1.45:1,bright?1.45:1);}
 const spheres:THREE.Mesh[]=[];scene.traverse(o=>{if((o as THREE.Mesh).isMesh&&o.userData.id)spheres.push(o as THREE.Mesh);if((o as THREE.Line).isLine&&o.parent?.visible){const line=o as THREE.Line;const pos=line.geometry.attributes.position;ctx.strokeStyle='#6c89933d';ctx.lineWidth=.65;ctx.beginPath();let prev=false;for(let i=0;i<pos.count;i++){const v=new THREE.Vector3(pos.getX(i),pos.getY(i),pos.getZ(i)).applyMatrix4(line.matrixWorld).sub(camera.position).applyQuaternion(cameraInv);if(v.z>=-.01){prev=false;continue;}const x=w/2+v.x/-v.z*f,y=h/2-v.y/-v.z*f;if(prev)ctx.lineTo(x,y);else ctx.moveTo(x,y);prev=true;}ctx.stroke();}});
 spheres.sort((a,b)=>b.getWorldPosition(new THREE.Vector3()).distanceToSquared(camera.position)-a.getWorldPosition(new THREE.Vector3()).distanceToSquared(camera.position));
 const forward=new THREE.Vector3(0,0,-1).applyQuaternion(camera.quaternion),right=new THREE.Vector3(1,0,0).applyQuaternion(camera.quaternion),up=new THREE.Vector3(0,1,0).applyQuaternion(camera.quaternion);
 for(const mesh of spheres){const center=mesh.getWorldPosition(new THREE.Vector3()),v=center.clone().sub(camera.position).applyQuaternion(cameraInv),r=(mesh.geometry as THREE.SphereGeometry).parameters.radius*mesh.getWorldScale(new THREE.Vector3()).x;if(v.z>=-r*.2)continue;const sx=w/2+v.x/-v.z*f,sy=h/2-v.y/-v.z*f;const size=f*r/Math.max(r*.1,Math.sqrt(Math.max(.001,v.z*v.z-r*r)));if(sx+size<0||sx-size>w||sy+size<0||sy-size>h)continue;
 const mat=mesh.material as THREE.MeshPhongMaterial,map=this.texture(mat.map),fallback=mat.color||new THREE.Color('#8296a5');const isSun=mesh.userData.id==='sun';
 let ring:THREE.Mesh|null=null;if(mesh.userData.id==='saturn')mesh.parent!.traverse(o=>{if((o as THREE.Mesh).geometry?.type==='RingGeometry')ring=o as THREE.Mesh;});
 const drawRing=(front:boolean)=>{if(!ring)return;const rr=ring as THREE.Mesh,texture=this.texture((rr.material as THREE.MeshPhongMaterial).map);const rp=(rr.geometry as THREE.RingGeometry).parameters;
 for(let band=0;band<28;band++){const inner=rp.innerRadius+(rp.outerRadius-rp.innerRadius)*band/28,outer=inner+(rp.outerRadius-rp.innerRadius)/28*1.03;const ti=texture?Math.min(texture.width-1,Math.floor(band/28*texture.width)):0,idx=texture?((Math.floor(texture.height/2)*texture.width+ti)*4):0;const red=texture?texture.data[idx]:197,green=texture?texture.data[idx+1]:176,blue=texture?texture.data[idx+2]:145,alpha=texture?texture.data[idx+3]/255:.7;if(alpha<.08)continue;ctx.fillStyle=`rgba(${red},${green},${blue},${alpha*(front?.78:.55)})`;
 for(let j=0;j<64;j++){const angle=j/64*Math.PI*2,next=(j+1.04)/64*Math.PI*2;const mid=new THREE.Vector3(Math.cos(angle)*(inner+outer)/2,Math.sin(angle)*(inner+outer)/2,0).applyMatrix4(rr.matrixWorld);if((mid.distanceToSquared(camera.position)<center.distanceToSquared(camera.position))!==front)continue;const pts=[[inner,angle],[outer,angle],[outer,next],[inner,next]].map(([rad,a])=>new THREE.Vector3(Math.cos(a)*rad,Math.sin(a)*rad,0).applyMatrix4(rr.matrixWorld).sub(camera.position).applyQuaternion(cameraInv));if(pts.some(p=>p.z>=0))continue;ctx.beginPath();pts.forEach((p,i)=>{const x=w/2+p.x/-p.z*f,y=h/2-p.y/-p.z*f;i?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.closePath();ctx.fill();}}};
 drawRing(false);
 if(size<1.5){ctx.fillStyle='#b8c4d2';ctx.beginPath();ctx.arc(sx,sy,1,0,Math.PI*2);ctx.fill();continue;}
 const bound=Math.min(size*1.035,Math.max(w,h)*2),left=sx-bound,top=sy-bound;const resolution=this.globe.width;const img=this.gctx.createImageData(resolution,resolution),data=img.data;const inv=mesh.getWorldQuaternion(new THREE.Quaternion()).invert();const rot=new THREE.Matrix4().makeRotationFromQuaternion(inv).elements;const oc=camera.position.clone().sub(center),c=oc.lengthSq()-r*r;const sun=center.clone().negate().normalize();const cloud=mesh.userData.id==='earth'&&mesh.children[0]?this.texture((mesh.children[0] as THREE.Mesh<THREE.SphereGeometry,THREE.MeshPhongMaterial>).material.alphaMap):null;
 for(let py=0;py<resolution;py++)for(let px=0;px<resolution;px++){const dx=(left+(px+.5)/resolution*bound*2-w/2)/f,dy=-(top+(py+.5)/resolution*bound*2-h/2)/f;
 let rx=forward.x+right.x*dx+up.x*dy,ry=forward.y+right.y*dx+up.y*dy,rz=forward.z+right.z*dx+up.z*dy;const len=Math.hypot(rx,ry,rz);rx/=len;ry/=len;rz/=len;const bb=oc.x*rx+oc.y*ry+oc.z*rz,disc=bb*bb-c;if(disc<0)continue;const t=-bb-Math.sqrt(disc);if(t<0)continue;const nx=(oc.x+rx*t)/r,ny=(oc.y+ry*t)/r,nz=(oc.z+rz*t)/r;const lx=rot[0]*nx+rot[4]*ny+rot[8]*nz,ly=rot[1]*nx+rot[5]*ny+rot[9]*nz,lz=rot[2]*nx+rot[6]*ny+rot[10]*nz;
 const u=((Math.atan2(lz,-lx)/(Math.PI*2))%1+1)%1,vv=Math.acos(Math.max(-1,Math.min(1,ly)))/Math.PI;const tx=map?Math.min(map.width-1,Math.floor(u*map.width)):0,ty=map?Math.min(map.height-1,Math.floor(vv*map.height)):0,idx=map?(ty*map.width+tx)*4:0;
 const diffuse=Math.max(0,nx*sun.x+ny*sun.y+nz*sun.z),terminator=Math.pow(diffuse,.72);const light=isSun?1.04:.045+terminator*1.04;const index=(py*resolution+px)*4;let cr=map?map.data[idx]:fallback.r*255,cg=map?map.data[idx+1]:fallback.g*255,cb=map?map.data[idx+2]:fallback.b*255;
 if(cloud){const ci=(Math.min(cloud.height-1,Math.floor(vv*cloud.height))*cloud.width+Math.min(cloud.width-1,Math.floor(u*cloud.width)))*4;const a=cloud.data[ci]/255*.55;cr=cr*(1-a)+240*a;cg=cg*(1-a)+247*a;cb=cb*(1-a)+255*a;}
 data[index]=Math.min(255,cr*light);data[index+1]=Math.min(255,cg*light);data[index+2]=Math.min(255,cb*light);data[index+3]=255;}
 this.gctx.putImageData(img,0,0);
 if(mesh.userData.id==='earth'){const g=ctx.createRadialGradient(sx,sy,size*.955,sx,sy,size*1.025);g.addColorStop(0,'#337ddd00');g.addColorStop(.58,'#65b3ef0d');g.addColorStop(.84,'#9bd4ff24');g.addColorStop(1,'#337ddd00');ctx.fillStyle=g;ctx.fillRect(left,top,bound*2,bound*2);}
 if(isSun){const g=ctx.createRadialGradient(sx,sy,size*.86,sx,sy,size*1.34);g.addColorStop(0,'#fff4c84f');g.addColorStop(.22,'#ffd27a24');g.addColorStop(.62,'#ff9b2a0b');g.addColorStop(1,'#ff721000');ctx.fillStyle=g;ctx.fillRect(sx-size*1.34,sy-size*1.34,size*2.68,size*2.68);}
 ctx.drawImage(this.globe,left,top,bound*2,bound*2);drawRing(true);
 }
 }
}
